// server.js
require('dotenv').config();
const express = require('express');
const nodemailer = require('nodemailer');
const bodyParser = require('body-parser');
const cors = require('cors');

const app = express();
const PORT = process.env.PORT || 5000;

app.use(cors());
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: true }));

// Nodemailer configuration
const transporter = nodemailer.createTransport({
    service: 'gmail',
    auth: {
        user: process.env.EMAIL_USER,
        pass: process.env.EMAIL_PASS
    }
});

app.post('/api/send_email', (req, res) => {
    const { name, phone, service, email } = req.body;

    const mailOptions = {
        from: process.env.EMAIL_USER,
        to: 'divyaneela75@gmail.com', // Replace with your email
        subject: 'New Service Quote Request',
        html: `
        <div style="font-family: Arial, sans-serif; color: #333; max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #e0e0e0; border-radius: 8px;">
            <h2 style="color: #4CAF50; font-size: 24px; margin-bottom: 20px;">New User Registration</h2>
            <p style="font-size: 16px; margin-bottom: 20px;">You have received a new user request with the following details:</p>

            <div style="margin-bottom: 12px;">
                <strong style="display: block; font-size: 16px; color: #4CAF50;">Name:</strong>
                <span style="font-size: 16px; color: #333;">${name}</span>
            </div>

            <div style="margin-bottom: 12px;">
                <strong style="display: block; font-size: 16px; color: #4CAF50;">Phone:</strong>
                <span style="font-size: 16px; color: #333;">${phone}</span>
            </div>

            <div style="margin-bottom: 12px;">
                <strong style="display: block; font-size: 16px; color: #4CAF50;">Service Needed:</strong>
                <span style="font-size: 16px; color: #333;">${service}</span>
            </div>

            <div style="margin-bottom: 12px;">
                <strong style="display: block; font-size: 16px; color: #4CAF50;">Email:</strong>
                <span style="font-size: 16px; color: #333;">${email}</span>
            </div>

            <p style="margin-top: 20px; font-size: 14px; color: #555;">This email was automatically generated by your website's contact form.</p>
        </div>
    `
    };

    transporter.sendMail(mailOptions, (error, info) => {
        if (error) {
            return res.status(500).json({ message: 'Failed to send message' });
        }
        res.status(200).json({ message: 'Your request has been received! We’ll be in touch soon.' });
    });
});

app.listen(PORT, () => {
    console.log(`Server is running on port ${PORT}`);
});
