// server.js
require('dotenv').config();
const express = require('express');
const nodemailer = require('nodemailer');
const bodyParser = require('body-parser');
const cors = require('cors');

const app = express();
const PORT = process.env.PORT || 5000;

app.use(cors());
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: true }));

// Nodemailer configuration
const transporter = nodemailer.createTransport({
    service: 'gmail',
    auth: {
        user: process.env.EMAIL_USER,
        pass: process.env.EMAIL_PASS
    }
});

app.post('/api/send_email', (req, res) => {
    const { name, phone, service, email } = req.body;

    const mailOptions = {
        from: process.env.EMAIL_USER,
        to: 'divyaneela75@gmail.com', // Replace with your email
        subject: 'New Service Quote Request',
        html: `
            <div style="font-family: Arial, sans-serif; color: #333; max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #e0e0e0; border-radius: 8px;">
            <h2 style="color: #4CAF50; font-size: 24px; margin-bottom: 20px;">New User Registration</h2>
            <p style="font-size: 16px; margin-bottom: 20px;">You have received a new user request:</p>
            <table style="width: 100%; border-collapse: collapse; font-size: 16px;">
                <tr>
                    <td style="padding: 8px; font-weight: bold; background-color: #f8f8f8; border: 1px solid #ddd;">Name:</td>
                    <td style="padding: 8px; border: 1px solid #ddd;">${name}</td>
                </tr>
                <tr>
                    <td style="padding: 8px; font-weight: bold; background-color: #f8f8f8; border: 1px solid #ddd;">Phone:</td>
                    <td style="padding: 8px; border: 1px solid #ddd;">${phone}</td>
                </tr>
                <tr>
                    <td style="padding: 8px; font-weight: bold; background-color: #f8f8f8; border: 1px solid #ddd;">Service Needed:</td>
                    <td style="padding: 8px; border: 1px solid #ddd;">${service}</td>
                </tr>
                <tr>
                    <td style="padding: 8px; font-weight: bold; background-color: #f8f8f8; border: 1px solid #ddd;">Email:</td>
                    <td style="padding: 8px; border: 1px solid #ddd;">${email}</td>
                </tr>
            </table>
            <p style="margin-top: 20px; font-size: 14px; color: #555;">This email was automatically generated by your website's contact form.</p>
        </div>
        `
    };

    transporter.sendMail(mailOptions, (error, info) => {
        if (error) {
            return res.status(500).json({ message: 'Failed to send message' });
        }
        res.status(200).json({ message: 'Your request has been received! We’ll be in touch soon.' });
    });
});

app.listen(PORT, () => {
    console.log(`Server is running on port ${PORT}`);
});
